use mysql;

/* creating table */
create table t_plans (id MEDIUMINT NOT NULL ,
BUSINESS_YEAR year(4),
STATE_CODE varchar(7),
ISSUER_NAME varchar(50),
ISSUER_ID int(5),
BENEFIT_PACKAGE_ID varchar(50),
MARKET_COVERAGE varchar(15),
DENTAL_ONLY_PLAN int(1),
STANDARD_COMPONENT_ID varchar(19),
PLAN_MARKETING_NAME varchar(100),
HIOS_PRODUCT_ID varchar(15),
HPID varchar(100),
NETWORK_ID varchar(11),
SERVICE_AREA_ID varchar(11),
FORMULARY_ID varchar(11),
IS_IT_A_NEW_PLAN int(1),
PLAN_TYPE varchar(8),
METAL_LEVEL varchar(11),
UNIQUE_PLAN_DESIGN int(1),
QHP_NONQHP_TYPE_ID varchar(9),
IS_NOTICE_REQUIRED_FOR_PREGNACY int(1),
IS_REFERRAL_REQUIRED_FOR_SPECIALIST int(1),
SPECIALIST_REQUIRING_REFERRAL varchar(50),
PLAN_LEVEL_EXCLUSIONS varchar(100),
IS_HSA_ELIGIBLE int(1),
HSA_OR_HRA_EMPLOYER_CONTRIBUTION varchar(100),
HSA_OR_HRA_EMPLOYER_CONTRIBUTION_AMOUNT varchar(100),
CHILD_ONLY_OFFERING varchar(22),
CHILD_ONLY_PLAN_ID varchar(100),
WELLNESS_PROGRAM_OFFERED int(1),
DISEASE_MANAGEMENT_PROGRAMS_OFFERED varchar(100),
EHB_PEDIATRIC_DENTAL_APPORTIONMENT_QUANTITY float(5,2),
IS_GUARANTEED_RATE varchar(100),
SPECIALITY_DRUG_MAXIMUM_COINSURANCE varchar(100),
INPATIENT_COPAYMENT_MAXIMUM_DAYS varchar(100),
BEGIN_PRIMARY_CARE_COST_SHARING_AFTER_NUMBER_OF_VISITS int(1),
BEGIN_PRIMARY_CARE_DEDUCTIBLE_COINSURANCE_AFTER_NUMBER_OF_COPAYS int(1),
PLAN_EFFECTIVE_DATE date  ,
PLAN_EXPIRATION_DATE date  ,
OUT_OF_COUNTRY_COVERAGE int(1),
OUT_OF_COUNTRY_COVERAGE_DESCRIPTION varchar(50),
OUT_OF_SERVICE_AREA_COVERAGE int(1),
OUT_OF_SERVICE_AREA_COVERAGE_DESCRIPTION varchar(50),
NATIONAL_NETWORK int(1),
PLAN_ID varchar(22),
CSR_VARIATION_TYPE varchar(29),
ISSUER_ACTUARIAL_VALUE varchar(9),
AV_CALCULATOR_OUTPUT_NUMBER float(11,9),
MEDICAL_DRUG_DEDUCTIBLES_INTEGRATED int(1),
MEDICAL_DRUG_MAXIMUM_OUT_OF_POCKET_INTEGRATED int(1),
MULTIPLE_NETWORK_TIERS int(1),
FIRST_TIER_UTILIZATION varchar(6),
SECOND_TIER_UTILIZATION varchar(100),
TEHB_INN_TIER_1_INDIVIDUAL_MOOP int(6),
TEHB_INN_TIER_1_FAMILY_MOOP varchar(100),
TEHB_INN_TIER_2_INDIVIDUAL_MOOP int(5),
TEHB_INN_TIER_2_FAMILY_MOOP varchar(100),
TEHB_OUT_OF_NET_INDIVIDUAL_MOOP int(19),
TEHB_OUT_OF_NET_FAMILY_MOOP varchar(100),
TEHB_COMB_INN_OON_INDIVIDUAL_MOOP int(5),
TEHB_COMB_INN_OON_FAMILY_MOOP varchar(100),
TEHB_DED_INN_TIER_1_INDIVIDUAL int(5),
TEHB_DED_INN_TIER_1_FAMILY varchar(100),
TEHB_DED_INN_TIER_1_COINSURANCE varchar(8),
TEHB_DED_INN_TIER_2_INDIVIDUAL varchar(100),
TEHB_DED_INN_TIER_2_FAMILY varchar(100),
TEHB_DED_INN_TIER_2_COINSURANCE varchar(100),
TEHB_DED_OUT_OF_NET_INDIVIDUAL int(5),
TEHB_DED_OUT_OF_NET_FAMILY varchar(100),
TEHB_DED_OUT_COMB_INN_OON_INDIVIDUAL int(5),
TEHB_DED_OUT_COMB_INN_OON_FAMILY varchar(100),
PRIMARY KEY (id));

/* inserting data */
insert into t_plans
(
id 
,BUSINESS_YEAR 
,STATE_CODE 
,ISSUER_NAME 
,ISSUER_ID 
,BENEFIT_PACKAGE_ID 
,MARKET_COVERAGE 
,DENTAL_ONLY_PLAN 
,STANDARD_COMPONENT_ID 
,PLAN_MARKETING_NAME 
,HIOS_PRODUCT_ID 
,HPID 
,NETWORK_ID 
,SERVICE_AREA_ID 
,FORMULARY_ID 
,IS_IT_A_NEW_PLAN 
,PLAN_TYPE
,METAL_LEVEL 
,UNIQUE_PLAN_DESIGN 
,QHP_NONQHP_TYPE_ID
,IS_NOTICE_REQUIRED_FOR_PREGNACY 
,IS_REFERRAL_REQUIRED_FOR_SPECIALIST 
,SPECIALIST_REQUIRING_REFERRAL
,PLAN_LEVEL_EXCLUSIONS
,IS_HSA_ELIGIBLE 
,HSA_OR_HRA_EMPLOYER_CONTRIBUTION 
,HSA_OR_HRA_EMPLOYER_CONTRIBUTION_AMOUNT
,CHILD_ONLY_OFFERING 
,CHILD_ONLY_PLAN_ID 
,WELLNESS_PROGRAM_OFFERED 
,DISEASE_MANAGEMENT_PROGRAMS_OFFERED 
,EHB_PEDIATRIC_DENTAL_APPORTIONMENT_QUANTITY 
,IS_GUARANTEED_RATE 
,SPECIALITY_DRUG_MAXIMUM_COINSURANCE 
,INPATIENT_COPAYMENT_MAXIMUM_DAYS 
,BEGIN_PRIMARY_CARE_COST_SHARING_AFTER_NUMBER_OF_VISITS
,BEGIN_PRIMARY_CARE_DEDUCTIBLE_COINSURANCE_AFTER_NUMBER_OF_COPAYS
,PLAN_EFFECTIVE_DATE 
,PLAN_EXPIRATION_DATE  
,OUT_OF_COUNTRY_COVERAGE 
,OUT_OF_COUNTRY_COVERAGE_DESCRIPTION
,OUT_OF_SERVICE_AREA_COVERAGE 
,OUT_OF_SERVICE_AREA_COVERAGE_DESCRIPTION 
,NATIONAL_NETWORK
,PLAN_ID 
,CSR_VARIATION_TYPE 
,ISSUER_ACTUARIAL_VALUE 
,AV_CALCULATOR_OUTPUT_NUMBER 
,MEDICAL_DRUG_DEDUCTIBLES_INTEGRATED 
,MEDICAL_DRUG_MAXIMUM_OUT_OF_POCKET_INTEGRATED
,MULTIPLE_NETWORK_TIERS 
,FIRST_TIER_UTILIZATION 
,SECOND_TIER_UTILIZATION 
,TEHB_INN_TIER_1_INDIVIDUAL_MOOP 
,TEHB_INN_TIER_1_FAMILY_MOOP 
,TEHB_INN_TIER_2_INDIVIDUAL_MOOP
,TEHB_INN_TIER_2_FAMILY_MOOP
,TEHB_OUT_OF_NET_INDIVIDUAL_MOOP 
,TEHB_OUT_OF_NET_FAMILY_MOOP 
,TEHB_COMB_INN_OON_INDIVIDUAL_MOOP 
,TEHB_COMB_INN_OON_FAMILY_MOOP 
,TEHB_DED_INN_TIER_1_INDIVIDUAL 
,TEHB_DED_INN_TIER_1_FAMILY 
,TEHB_DED_INN_TIER_1_COINSURANCE
,TEHB_DED_INN_TIER_2_INDIVIDUAL
,TEHB_DED_INN_TIER_2_FAMILY 
,TEHB_DED_INN_TIER_2_COINSURANCE
,TEHB_DED_OUT_OF_NET_INDIVIDUAL 
,TEHB_DED_OUT_OF_NET_FAMILY 
,TEHB_DED_OUT_COMB_INN_OON_INDIVIDUAL 
,TEHB_DED_OUT_COMB_INN_OON_FAMILY
)
 select 
id 
,BUSINESS_YEAR 
,STATE_CODE 
,ISSUER_NAME 
,ISSUER_ID 
,BENEFIT_PACKAGE_ID 
,MARKET_COVERAGE 
,DENTAL_ONLY_PLAN 
,STANDARD_COMPONENT_ID 
,PLAN_MARKETING_NAME 
,HIOS_PRODUCT_ID 
,HPID 
,NETWORK_ID 
,SERVICE_AREA_ID 
,FORMULARY_ID 
,IS_IT_A_NEW_PLAN 
,PLAN_TYPE
,METAL_LEVEL 
,UNIQUE_PLAN_DESIGN 
,QHP_NONQHP_TYPE_ID
,IS_NOTICE_REQUIRED_FOR_PREGNACY 
,IS_REFERRAL_REQUIRED_FOR_SPECIALIST 
,SPECIALIST_REQUIRING_REFERRAL
,PLAN_LEVEL_EXCLUSIONS
,IS_HSA_ELIGIBLE 
,HSA_OR_HRA_EMPLOYER_CONTRIBUTION 
,HSA_OR_HRA_EMPLOYER_CONTRIBUTION_AMOUNT
,CHILD_ONLY_OFFERING 
,CHILD_ONLY_PLAN_ID 
,WELLNESS_PROGRAM_OFFERED 
,DISEASE_MANAGEMENT_PROGRAMS_OFFERED 
,EHB_PEDIATRIC_DENTAL_APPORTIONMENT_QUANTITY 
,IS_GUARANTEED_RATE 
,SPECIALITY_DRUG_MAXIMUM_COINSURANCE 
,INPATIENT_COPAYMENT_MAXIMUM_DAYS 
,BEGIN_PRIMARY_CARE_COST_SHARING_AFTER_NUMBER_OF_VISITS
,BEGIN_PRIMARY_CARE_DEDUCTIBLE_COINSURANCE_AFTER_NUMBER_OF_COPAYS
,PLAN_EFFECTIVE_DATE 
,PLAN_EXPIRATION_DATE
,OUT_OF_COUNTRY_COVERAGE 
,OUT_OF_COUNTRY_COVERAGE_DESCRIPTION
,OUT_OF_SERVICE_AREA_COVERAGE 
,OUT_OF_SERVICE_AREA_COVERAGE_DESCRIPTION 
,NATIONAL_NETWORK
,PLAN_ID 
,CSR_VARIATION_TYPE 
,ISSUER_ACTUARIAL_VALUE 
,AV_CALCULATOR_OUTPUT_NUMBER 
,MEDICAL_DRUG_DEDUCTIBLES_INTEGRATED 
,MEDICAL_DRUG_MAXIMUM_OUT_OF_POCKET_INTEGRATED
,MULTIPLE_NETWORK_TIERS 
,FIRST_TIER_UTILIZATION 
,SECOND_TIER_UTILIZATION 
,TEHB_INN_TIER_1_INDIVIDUAL_MOOP 
,TEHB_INN_TIER_1_FAMILY_MOOP 
,TEHB_INN_TIER_2_INDIVIDUAL_MOOP
,TEHB_INN_TIER_2_FAMILY_MOOP
,TEHB_OUT_OF_NET_INDIVIDUAL_MOOP 
,TEHB_OUT_OF_NET_FAMILY_MOOP 
,TEHB_COMB_INN_OON_INDIVIDUAL_MOOP 
,TEHB_COMB_INN_OON_FAMILY_MOOP 
,TEHB_DED_INN_TIER_1_INDIVIDUAL 
,TEHB_DED_INN_TIER_1_FAMILY 
,TEHB_DED_INN_TIER_1_COINSURANCE
,TEHB_DED_INN_TIER_2_INDIVIDUAL
,TEHB_DED_INN_TIER_2_FAMILY 
,TEHB_DED_INN_TIER_2_COINSURANCE
,TEHB_DED_OUT_OF_NET_INDIVIDUAL 
,TEHB_DED_OUT_OF_NET_FAMILY 
,TEHB_DED_OUT_COMB_INN_OON_INDIVIDUAL 
,TEHB_DED_OUT_COMB_INN_OON_FAMILY
from Plans_NY_MA where PLAN_EXPIRATION_DATE = '2016-12-31'
;

